# DS Bootcamp Fall 2025
# Week 2 Exercise
#### Submitted by Meenakshi Madhu (MM14029)

In [6]:
import numpy as np
import pandas as pd

## HW Questions (Numpy):

### 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [23]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
B = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(A)
print(B)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [24]:
# array X stacking A, B vertically
X = np.vstack((A,B))

print("X = \n", X)
print("\n Shape of X = ", X.shape)

X = 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [ 2  4  6  8 10 12 14 16 18 20]]

 Shape of X =  (2, 10)


In [25]:
# array Y stacking A, B horizontally
Y = np.hstack((A,B))

print("Y = \n", Y)
print("\n Shape of Y = ", Y.shape)

Y = 
 [ 1  2  3  4  5  6  7  8  9 10  2  4  6  8 10 12 14 16 18 20]

 Shape of Y =  (20,)


### 2. Find common elements between A and B. [Hint : Intersection of two sets]

In [27]:
intersection = np.intersect1d(A, B)
print(f"Intersection of A and B: {intersection}")

Intersection of A and B: [ 2  4  6  8 10]


### 3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [28]:
result = A[(A >= 5) & (A <= 10)]
print(result)

[ 5  6  7  8  9 10]


### 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [29]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [35]:
sepallength_col = iris_2d[:, 0]
petallength_col = iris_2d[:, 2]
filtered_rows = iris_2d[(petallength_col > 1.5) & (sepallength_col < 5.0)]
filtered_rows

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

### Optional Practice Question

#### Find the mean of a numeric column grouped by a categorical column in a 2D numpy array


In [80]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

output = []

species = np.unique(grouping_column)

for s in species:
    indices = np.where(grouping_column == s) 
    mean_value = numeric_column[indices].mean()
    output.append((s, mean_value))

output


[(b'Iris-setosa', np.float64(3.418)),
 (b'Iris-versicolor', np.float64(2.7700000000000005)),
 (b'Iris-virginica', np.float64(2.974))]

## HW Questions (Pandas):

### 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [43]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [40]:
# select every 20th row (filter by step)
df_20 = df.iloc[::20]
df_20

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
20     Chrysler  LeBaron  Compact       14.5   15.8       17.1      23.0   
40        Honda  Prelude   Sporty       17.0   19.8       22.7      24.0   
60      Mercury   Cougar  Midsize       14.9   14.9       14.9      19.0   
80       Subaru   Loyale    Small       10.5   10.9       11.3      25.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
20         28.0  Driver & Passenger      Front  ...        6.0   183.0   
40         31.0  Driver & Passenger      Front  ...        4.0   175.0   
60         26.0                 NaN       Rear  ...        5.0   199.0   
80         30.0                 NaN        4WD  ...        5.0   175.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
20      104.0   68.0         41.0           30.5          14.0  3085.0   
40      100.0   70.0         39.0           23.5           8.0  2865.0   
60      113.0   73.0         38.0           28.0          15.0  3610.0   
80       97.0   65.0         35.0           27.5          15.0  2490.0   

     Origin              Make  
0   non-USA     Acura Integra  
20      USA  Chrysler LeBaron  
40  non-USA     Honda Prelude  
60      USA    Mercury Cougar  
80  non-USA     Subaru Loyale  

[5 rows x 27 columns]

In [42]:
# filter columns
result = df_20[['Manufacturer', 'Model', 'Type']]
result

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

### 2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [45]:
# find means of both columns
min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()

In [51]:
# replace missing values
df['Min.Price'] = df['Min.Price'].fillna(min_price_mean)
df['Max.Price'] = df['Max.Price'].fillna(max_price_mean)

In [50]:
print(df[['Min.Price', 'Max.Price']].isna().sum())

Min.Price    0
Max.Price    0
dtype: int64


### 3. How to get the rows of a dataframe with row sum > 100?

In [71]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

0   1   2   3
0   24  39  14  25
1   27  16  11  16
2   36  30  19  37
3   21  38  20  23
4   26  22  29  26
5   38  33  32  14
6   14  37  33  15
7   11  29  18  34
8   14  33  13  16
9   33  32  38  35
10  19  21  16  24
11  21  16  16  25
12  38  11  14  32
13  36  37  23  36
14  24  27  35  26

In [72]:
# finding a row's sum:
result = df[df.sum(axis=1)>100]
result

0   1   2   3
0   24  39  14  25
2   36  30  19  37
3   21  38  20  23
4   26  22  29  26
5   38  33  32  14
9   33  32  38  35
13  36  37  23  36
14  24  27  35  26

In [73]:
# added row_sum
result = result.assign(row_sum=result.sum(axis=1))
result

0   1   2   3  row_sum
0   24  39  14  25      102
2   36  30  19  37      122
3   21  38  20  23      102
4   26  22  29  26      103
5   38  33  32  14      117
9   33  32  38  35      138
13  36  37  23  36      132
14  24  27  35  26      112